ZillaApp = WebMIDIPlayer
ZLWASM_ASSETS_EMBED = 1
ZLEMSCRIPTEN_ASSETS_EMBED = 1
ZLEMSCRIPTEN_ADD_EXPORTS = _WMP_LoadSoundFont _WMP_LoadMidi
ZLEMSCRIPTEN_ALLOW_MEMORY_GROWTH = 1
ZILLALIB_PATH = ../ZillaLib
include $(ZILLALIB_PATH)/Makefile
