echo Building \'example1-osx-`uname -m`\' ...
clang -std=c99 -Wall example1.c -lm -ldl -lpthread -framework CoreServices -framework CoreAudio -framework AudioUnit -Wno-unknown-warning-option -o example1-osx-`uname -m`
echo Building \'example2-osx-`uname -m`\' ...
clang -std=c99 -Wall example2.c -lm -ldl -lpthread -framework CoreServices -framework CoreAudio -framework AudioUnit -Wno-unknown-warning-option -o example2-osx-`uname -m`
echo Building \'example3-osx-`uname -m`\' ...
clang -std=c99 -Wall example3.c -lm -ldl -lpthread -framework CoreServices -framework CoreAudio -framework AudioUnit -Wno-unknown-warning-option -o example3-osx-`uname -m`
echo Done!
